name: Testes Atutomáticos Backend

on: pull_request

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Acess backend directory
        run: cd backend

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/krypton"

      - name: Install dependencies, using npm ci
        run: npm ci

      - name: Run tests
        run: npm run test
